apiVersion: apps/v1
kind: Deployment
metadata:
  name: household-inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: household-inventory
      name: household-inventory-app
  template:
    metadata:
      labels:
        app: household-inventory
        name: household-inventory-app
    spec:
      containers:
      - name: household-inventory
        image: household-inventory
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: household-inventory-lb
spec:
  selector:
    app: household-inventory
    name: household-inventory-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer