apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  dbHost: aABvAHUAcwBlAGgAbwBsAGQALQBpAG4AdgBlAG4AdABvAHIAeQAtAHEAYQAuAGMAdQB0AHoAYwB1AHEAdQBpADIAZwB5AC4AdQBzAC0AZQBhAHMAdAAtADEALgByAGQAcwAuAGEAbQBhAHoAbwBuAGEAdwBzAC4AYwBvAG0A
  username: YwByAGUAcwBsAG8AZwBhAF8AcQBhAA==
  password: YwByAGUAcwBsAG8AZwBhAF8AaABpAF8AcQBhAF8AMQAyADIAMwA=