server:
  port: 8080
  servlet:
    context-path: /householdinventory
  
spring:
  jackson:
    serialization:
      indent-output: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
              